### ISSUE TITLE
Network keeps "Connecting" to wifi although wpa_supplicant already knows that they "key" is wrong

### ISSUE THREAD

**Issue by kobliha** [agama-project/agama#1051]
![Network-wrong-key-keeps-connecting](https://github.com/openSUSE/agama/assets/463995/dfc31ad2-2a4a-4c89-a7f3-2258c9f94658)

When a wrong wifi key is provided, network keeps in loop showing that it's still connecting. This may be true, but the underlying layer already knows that the key was wrong after 10 seconds.

It would be great to stop connecting and provide the info to the user somehow. Maybe with possibility to re-enter the key. Maybe with the key entry already pre-filled. The user can always clikc the [<o>] eye button to check and validate the entered key and possibly change it.

**Comment by kobliha** [comment]
[wpa_supplicant.log](https://github.com/openSUSE/agama/files/14383083/wpa_supplicant.log)
Here's the wpa_supplicant.log

1. Unsuccessful auth
2. Successful auth

**Comment by kobliha** [comment]
So, as @teclator says, it's already mentioned at https://trello.com/c/ysy9NkN3 (internal link) at "What is missing" section.

**Comment by imobachgs** [comment]
This is no longer the case after the latest changes in network management. Hence I am closing this issue.

JFTR, https://github.com/agama-project/agama/blob/master/web/src/components/network/WifiConnectionForm.tsx#L100
