### ISSUE TITLE
Wrong UTC offset in the list of timezones

### ISSUE THREAD

**Issue by imobachgs** [agama-project/agama#1335]
Reported by @jreidinger:

> many countries has UTC even when their timezone is like UTC+2, so probably something is wrong at
> source data or during processing
>
> but I see when search e.g. for UTC-7

**Comment by imobachgs** [comment]
The offset is calculated at the client side: https://github.com/openSUSE/agama/blob/f9c0c0d24390825cbe36cb54950a93113828d616/web/src/utils.js#L355.

**Comment by mvidner** [comment]
@jreidinger I cannot see the problem now. Can you guide me to find it?
![agama-tzofs](https://github.com/openSUSE/agama/assets/102056/4b189bcb-db07-4d50-b9ee-8ea52e6c7481)

(BTW note how it shows the _current_ UTC offset, applying the daylight savings time.)

**Comment by imobachgs** [comment]
It happens only in some cases (I do not know how many). But some timezones are reported as UTC when they are not. Two examples: Atlantic/Canary (UTC+1) and Americas/Adak (UTC-9).

**Comment by dgdavid** [comment]
Just in case it might help, would worth having a look at https://github.com/date-fns/tz

Not only for usin it (I'd do if it make our code work as expected) but also for learning from its source code and tests, 

https://github.com/date-fns/tz/tree/main/src/tzOffset

**Comment by imobachgs** [comment]
The problem is fixed in #1646.
