### ISSUE TITLE
Empty web-UI URL https:// printed several times in case of no network

### ISSUE THREAD

**Issue by kobliha** [agama-project/agama#1347]
![web-URL-empty](https://github.com/openSUSE/agama/assets/463995/0b932758-1ade-4e4e-aee4-ff1c6cd3bbad)

How to reproduce

1. Boot Agama LiveCD without access to network
2. Switch to the console
3. You get `https://agama.local` and then simple empty `https://` several times

**Comment by imobachgs** [comment]
Thanks for the report! That problem was already addressed in #1515.

![no-network](https://github.com/user-attachments/assets/b57c6818-8090-4b69-8539-d139a7d88ca5)
