### ISSUE TITLE
rubygem-agama-yast: suggestion to split dbus service and files into a separate package

### ISSUE THREAD

**Issue by lkocman** [agama-project/agama#1427]
yes you can ship all those things through the gem ... but tbh it could also make sense to have the dbus service and its files in a different package that then jsut requires the rubygem-agama package

**Comment by mvidner** [comment]
@lkocman "it could make sense" is a bit weak, if it means more complex packaging and more work to do :wink: 

Do you have a more practical reason for the split?

**Comment by lkocman** [comment]
Let's reject this I no longer request the original reason.

**Comment by darix** [comment]
the point was very simple

you were shipping files there which arent really specific to the ruby version. so they could be living outside
