### ISSUE TITLE
Still missing Swedish 23th September 2024

### ISSUE THREAD

**Issue by bittin** [agama-project/agama#1629]
testing now with todays 23th Septembers iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-openSUSE.iso , more Swedish now at least, but its not fully complete yet but maybe there is some strings thats not on Weblate yet ?

**Comment by imobachgs** [comment]
Please, put some example so we can have a look.

**Comment by imobachgs** [comment]
Oh, and the link you posted is generic; it does not tell us which build you are using.

**Comment by bittin** [comment]
@imobachgs https://imgur.com/a/cIZXZDH here is a couple of examples that still have text in english, sorry still sick so was a bit lazy and that is the build from today so Agama 10 25.3

**Comment by imobachgs** [comment]
The untranslated strings are coming from the backend and they are translated in weblate.

**Comment by imobachgs** [comment]
#1642, #1643 and #1644 should fix those problems. There is only one glitch while displaying the language change progress, but that's a different topic we might need to address with some serious refactoring.

**Comment by imobachgs** [comment]
Oh, I almost forgot: the pattern descriptions in the software section are not translated because the repository does not contain any translation to Swedish.

**Comment by bittin** [comment]
This is still not fixed, just tried the Leap 16 Pre Alpha image

alright where to translate the pattern descriptions?
