### ISSUE TITLE
Arm boot clarification

### ISSUE THREAD

**Issue by lkocman** [agama-project/agama#1638]
Hello team,

a discussion around our current boot issue (Boot from disk entry) on Arm raised few questions

![image](https://github.com/user-attachments/assets/62631b77-847a-4ac9-98a8-a604b2d52922)
https://openqa.opensuse.org/tests/4503427#step/grub_test/28 shows boot and leap
While based on @guillaume_g it used to be `BOOT` instead of `boot` and `opensuse` instead of `leap`

I guess openQA needles would then just work, if we agree that boot from local bringing you to the setup on the screenshot is expected behavior.

Lubos

**Comment by ancorgs** [comment]
I have no idea. That's not setup by Agama or the YaST libraries. I guess you must ask our Grub2 experts.

**Comment by lkocman** [comment]
This was simply re-needled in openQA. Guillaume told me that this is more or less expected behavior.
