### ISSUE TITLE
Unexpected application Error! 404 Not Found

### ISSUE THREAD

**Issue by buzzmandt** [agama-project/agama#1664]
Agama returns an error screen with no way out. System reboot is required. From downloaded Leap 16.0 development build today. 

Easy to reproduce:

1. Start agama from iso
2. Select product (only tested leap and tumbleweed)
3. Change product
4. Hit Cancel
5. Unexpected Application Error! 404 not found as per screenshot

There's no button to press. Screen is dead with no way out but reboot/reset.

Tested on Virtualbox, and Virt manager/Qemu/kvm, all get the same result. Didn't test on hardware, had other issues keeping it from booting that I am working on and will report on if needed.

![Screenshot_20241010_175358](https://github.com/user-attachments/assets/08e79319-8cfa-45a7-b53d-2492d64d856c)

**Comment by imobachgs** [comment]
Thank you! I reproduced this one and it should be easy to fix. I will take care.

**Comment by imobachgs** [comment]
#1666 works around the problem. We need to find a better way, but the "Cancel" button should work now.

**Comment by buzzmandt** [comment]
Excellent. Thank you. I feel like I did something now :)

**Comment by dgdavid** [comment]
Interesting. I have reverted the hotfix in my local copy and I'm not able to reproduce the issue. I'd like to do so since it's something deserves a _final_ fix.

**Comment by imobachgs** [comment]
The problem is not there anymore. I will close the bug report.
