### ISSUE TITLE
X11 server does not start (missing drivers/firmware)

### ISSUE THREAD

**Issue by buzzmandt** [agama-project/agama#1665]
On 3 real hardware machines I get

`[ OK ] Started X11 Session`
`[  37.668759][ T3166] No iBFT detected.`

Progress is halted and system stops. I'd love to help trouble shoot this but I have no idea how.

2 older machines and 1 much newer one. All 3 are currently running tumbleweed but can't boot Agama. This was one Leap 16 pre-alpha downloaded this evening.

**Comment by imobachgs** [comment]
Hi! Where did you download the ISO from, please? Just to make sure that I check the same.

**Comment by buzzmandt** [comment]
From https://get.opensuse.org/leap/16.0/

**Comment by kobliha** [comment]
It's seems that the iBFT is just a red herring. I've experienced similar issue and it was actually the X server unable to start for missing video drivers from the media. To check that...

1. Switch to some console where you should see the root password to log in
2. Run `hwinfo --gfxcard` <-- if Driver Status: is inactive, try...
3. Driver Activation Cmd: `modprobe $that_driver` (in my case it's "i915")
4. If that fails, `dmesg` will tell a lot

Also checking with `less /var/log/Xorg.0.log` would tell you how far this got. Somewhere there will be a note what has failed and why. My bet is a missing file/s under _/lib/modules/*/kernel/drivers/media/_

**Comment by buzzmandt** [comment]
Tried on one... images with more details attached

`hwifno --gfxcard`
ATI Technologies Inc
Trinity [Radeon HD 7640G]
Driver info #0, radeon not active, activation cmd : "modprobe radeon"
Driver info #1, amdgpu not active, activation cmd: "modprobe amdgpu"

modprobe either gives and long list of errors about symbols missing

`less /var/log/Xorg.0.log`
"No such file or directory"

`cd /var/log/` enter
`dir`
returns the other picture attached. no Xorg anything listed.

log entries appear to be
alternatives.log
pbl.log
wpa_supplicant.log
![IMG_20241016_152639774](https://github.com/user-attachments/assets/f6cbc079-6450-4b63-b0d9-6d12256c1b14)
![IMG_20241016_153328028](https://github.com/user-attachments/assets/a81af105-5985-4990-9e6b-87b1204adab5)

**Comment by kobliha** [comment]
![modprobe radeon](https://github.com/user-attachments/assets/e060878e-4a15-4b31-bf85-adf5566a74af)

OK, so `modprobe radeon` on my system throws the same error: **cec** missing
This might be because of how my system is connected to the monitor (HDMI), but I believe it's the same issue.

Some more info about the drivers:
![modinfo - depends](https://github.com/user-attachments/assets/df1a8782-bea2-4507-a1d1-c2dd85eff786)

i915 is mine, the other ones are @buzzmandt's

**Comment by buzzmandt** [comment]
That long list of -2 errors is exactly what I was getting too. 
Don't know if it helps or not (more info is better) mine is a laptop with no external monitor attached.

**Comment by lslezak** [comment]
Fixed in #1790, the `cec.ko` driver and some more are now kept in the system.
