### ISSUE TITLE
`setup.sh` not working on a fresh installation

### ISSUE THREAD

**Issue by dgdavid** [agama-project/agama#1685]
When running ./setup-sh on a fresh openSUSE Tumbleweed installation, I'm facing two problems, 

* `./setup-services.sh: line 119: CI: unbound variable`, related to change introduced in https://github.com/agama-project/agama/commit/fac8bb6e7afc16feb63a2feb4b27f5dc1a9edfd0. Commenting lines added in linked commit leads to following problem
* `An error occurred while installing ruby-augeas (0.5.0), and Bundler cannot continue.` Which is quite similar error that was solved at https://github.com/agama-project/agama/pull/1565 for CI.

**Comment by imobachgs** [comment]
The `unbound variable` problem is because of the `-u` in `set -eu.` If we want to keep the `-u`, we need to set a default value for `CI`.

**Comment by dgdavid** [comment]
To reproduce the problem, please install a fresh openSUSE Tumbleweed and try to run the ./setup.sh

**Comment by lslezak** [comment]
You need to install rubygem-ruby-augeas from RPM before running the script. I'll update the script to install it automatically...

**Comment by lslezak** [comment]
Ah, the script prefers the RPM version only when running in CI, you need to run it with `CI=true`...

**Comment by imobachgs** [comment]
Then it will try to install the gems to `/usr,` which is not what I want on my system. And I will need to run the command as `root`.

**Comment by lslezak** [comment]
Yes, we probably do not want to do this outside CI... :worried:

**Comment by imobachgs** [comment]
Perhaps we could use distrobox to set up the development system: https://github.com/agama-project/agama/pull/1687.

**Comment by jreidinger** [comment]
problem with ruby augeas should be fixed with https://github.com/agama-project/agama/pull/1705 .

**Comment by imobachgs** [comment]
It should be fixed with #1687.
