### ISSUE TITLE
Incomplete OpenAPI data

### ISSUE THREAD

**Issue by lslezak** [agama-project/agama#1700]
## Use case

I created an online Agama demo at https://agama-online-demo.surge.sh/. I collected the testing data by recording the HTTP responses while clicking around in the browser. But that's inconvenient and fragile (you need to go through all Agama settings, if you miss something then the data is incomplete).

I'd like to automate that, the idea is to get the list of endpoints from the OpenAPI data and query all paths by a script.

But when comparing the current OpenAPI data and the data I got from the browser I found some inconsistencies which block this approach.

*Note: In this use case I'm interested only in the GET requests, the same problem or more problems might be with the POST/PUT/... requests.*

## Missing paths

These paths are missing in the OpenAPI:

- /api/manager/logs
- /api/network/connections/:id
- /api/network/state
- /api/network/wifi
- /api/software/issues/product
- /api/software/issues/software
- /api/storage/dasd/supported
- /api/storage/issues
- /api/storage/zfcp/supported
- /api/users/issues

## Missing /api prefix

Some OpenAPI paths miss the `/api` prefix:

- /l10n/locales
- /questions
- /users/first
- /users/root

**Comment by imobachgs** [comment]
Unfortunately, the OpenAPI has never been working at all. We recently did a ton of fixes (see #1564), but it is still a work in progress.

**Comment by mvidner** [comment]
The source for the demo is https://github.com/agama-project/agama/pull/1662

**Comment by imobachgs** [comment]
Most of the problems are already fixed by #1564. The `issues` endpoints are still missing.
