### ISSUE TITLE
Agama fails to load a profile that has a network section

### ISSUE THREAD

**Issue by serock** [agama-project/agama#1701]
I'm running Agama inside of Virtualbox 7.0.18 on openSUSE Leap 15.6. I tried using the Agama CLI from the latest Live ISO (agama-installer.x86_64-10.0.0-openSUSE-Build25.145.iso) to load a profile. If the profile has a **network** section, the profile fails to load:

```
agama:~ # agama profile validate n.json
The profile is valid
agama:~ # agama config load < n.json
Anyhow(Backend call failed with status 405 and text '')
```
The [n.json](https://github.com/user-attachments/files/17531010/n.json) profile that I'm trying to load is:

```json
{
  "user": {
    "fullName": "Jane Doe",
    "userName": "jane.doe",
    "password": "123456"
  },
  "product": {
    "id": "Tumbleweed"
  },
  "localization": {
    "language": "en_US.UTF-8",
    "keyboard": "us",
    "timezone": "America/New_York"
  },
  "network": {
    "connections": [
      {
        "id": "Wired connection 1"
      }
    ]
  }
}
```

If I remove the **network** section, Agama loads the profile.

**Comment by imobachgs** [comment]
Thanks for your report. #1702 should fix this issue. It should be available today in the [openSUSE image](https://agama-project.github.io/download).
