### ISSUE TITLE
install button when installing design problem

### ISSUE THREAD

**Issue by bittin** [agama-project/agama#1725]
![bild](https://github.com/user-attachments/assets/a63c73b3-ec9c-4bac-badb-bacec39053b7)

should the install button really still be here when the system is already installing?

**Comment by bittin** [comment]
a fix is waiting in: https://github.com/agama-project/agama/pull/1717

**Comment by dgdavid** [comment]
> a fix is waiting in: #1717

Which is now merged. Hopefully, the problem has gone. Thanks!

**Comment by bittin** [comment]
> a fix is waiting in: #1717

have been fixed now by @dgdavid so closing this bug

**Comment by bittin** [comment]
can verify its fixed in the 5th November iso: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-10.0.0-openSUSE-Build26.4.iso
