### ISSUE TITLE
can't be installed in gnome-boxes

### ISSUE THREAD

**Issue by bittin** [agama-project/agama#1726]
This iso can't be installed in gnome-boxes: https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-installer.x86_64-openSUSE.iso 

have time to try again on Wednesday or Friday this week if it have been fixed

**Comment by dgdavid** [comment]
Thanks @bittin 

If you still having the machine up, please try to collect the logs and upload them here. They might help us to see what is wrong.

**Comment by bittin** [comment]
[agama-logs-boxes.tar.gz](https://github.com/user-attachments/files/17616738/agama-logs-boxes.tar.gz)

**Comment by dgdavid** [comment]
#1727 should fix this issue. Thansk a ton @bittin for reporting it.

**Comment by bittin** [comment]
Can confirm, the installer works again, just installed Tumbleweed with it

**Comment by bittin** [comment]
and Slowroll/Leap all works

**Comment by imobachgs** [comment]
Thanks!
