### ISSUE TITLE
Agama UX: "Select" button in product selection scrolled out of sight

### ISSUE THREAD

**Issue by shundhammer** [agama-project/agama#1750]
## Problem

At the very first interactive Agama screen, the one button that gets the user out of this screen is scrolled out of sight by default:

![agama-product-selection-01-initial](https://github.com/user-attachments/assets/c87435f9-ca8a-43e2-9c52-4bc5832c9b29)

Since the vertical scrollbar in Firefox is so subtle that it is invisible unless you hover over it, there is no hint that there even is a button. A user might be tempted to think that it continues automatically when selecting a product, but no, that just selects it, it does not continue.

The user needs to know that he has to scroll down to make the button visible:

![agama-product-selection-03-scrolled](https://github.com/user-attachments/assets/e2e2dcf1-71f0-4197-b562-5c98ab645820)

But that is irritating. The main button of such a page should not disappear.

## Possible Solutions

The button might be part of a static page footer so it remains visible. Maybe the left part of that footer might even be transparent to avoid obscuring the page content there.

Since in this specific setup there is empty space on the right side, it might even be a static button at the bottom right, very much like those static "scroll to top" buttons on many web pages.

## Used Image

Build 28.1 ISO from https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/, downloaded on 2024-11-11.

**Comment by dgdavid** [comment]
As commented in IRC, this is already internally recorded as a Trello card to be prioritize. See https://trello.com/c/ZdOMjg3r (internal link).

Fortunately, radio buttons helps to hint users meanwhile.

Thanks!

**Comment by imobachgs** [comment]
Fixed in #1769.

**Comment by dgdavid** [comment]
> Fixed in #1769.

I would say _changed_ instead of _fixed_ :wink:

Now, the actions are always visible at the bottom of the viewport, which reduces the space available for the product list. I’ll add a more detailed comment in the near future, when I have time.
