### ISSUE TITLE
Agama starts in a super low resolution on Intel HD 620

### ISSUE THREAD

**Issue by lkocman** [agama-project/agama#1752]
One observation with testing install on a real HW.
I have relatively old Tuxedo laptop with Intel HD 620 and agama starts in a super low resolution there. You can see that centering is off (all is shifted to the right), and it's really uneasy to navigate on it.

One would expect such issues e.g. on NVIDIA, but not on Intel.

[agama-logs.tar.gz](https://github.com/user-attachments/files/17721299/agama-logs.tar.gz)

![IMG_1071](https://github.com/user-attachments/assets/98f8ad17-06d7-42c5-beeb-2d6f52acdf24)
![IMG_1072](https://github.com/user-attachments/assets/60766e10-9822-484d-ba76-35b93b4b40f6)
![IMG_1073](https://github.com/user-attachments/assets/8c93c095-507b-452c-be66-835290054d50)

![IMG_1070](https://github.com/user-attachments/assets/d1bf7834-d9fc-44b6-9b74-d26946ef02ef)

**Comment by lkocman** [comment]
We're using `/usr/bin/Xorg.bin -logfile /dev/null  which doesn't really help with debugging.`

**Comment by lkocman** [comment]
Perhaps very likely related #1665

**Comment by lkocman** [comment]
I'm using agama-installer.x86_64-10.0.0-openSUSE-Build27.12.iso from systemsmanagement:Agama:Devel. I believe from last Sunday.

**Comment by lkocman** [comment]
[Xorg.log](https://github.com/user-attachments/files/17721453/Xorg.log)

Xorg.log after tweaking the x11-autologin.service.

**Comment by lkocman** [comment]
I suppose this is the issue
```
[   172.200] (WW) Warning, couldn't open module intel
[   172.200] (EE) Failed to load module "intel" (module does not exist, 0)
```

**Comment by lslezak** [comment]
Looks like there missing drivers should be added to the ISO:

```
xf86-video-amdgpu
xf86-video-fbdev
xf86-video-intel
xf86-video-nv
xf86-video-vesa
```

This should cover the most common hardware.

Additionally we could add some virtualization drivers (if they do not take much space and are useful):

```
xf86-video-vmware
xf86-video-qxl
```

**Comment by lkocman** [comment]
I think so too, it could be also bunch of missing kernel firmware, but I'd start with listed drivers. 
Do we have a full list of firmware+drivers from old install image?

**Comment by jreidinger** [comment]
it should be ones in installation images https://github.com/openSUSE/installation-images/blob/fd8629fc4b4b5810b668881fa430c30cc81056f3/obs/installation-images.spec#L586

**Comment by lkocman** [comment]
So for tuxedo we're still in low res mode 800x600.

**Comment by lkocman** [comment]
Hmmm interesting worked on next boot of the new media :-) Now this finally looks nice. tested with agama-installer.x86_64-10.0.0-openSUSE-Build30.1.iso from agama:devel
![tuxedo](https://github.com/user-attachments/assets/870850fd-771a-4800-8fef-b178b67d738a)

**Comment by imobachgs** [comment]
Thanks for your confirmation. I am closing the bug.
