### ISSUE TITLE
installation with unset root password

### ISSUE THREAD

**Issue by lkocman** [agama-project/agama#1760]
A few users ended up with an unusable system without root access on our Leap 16.0 installation workshop

As it seems that if you define a user, there is no longer a requirement to set root password.
The user seem not to be privileged which basically leaves you with an unusable system without root password unset, and unusable sudo.

![image](https://github.com/user-attachments/assets/79dcc91e-d03e-4e85-a8c8-e1aab00dd0e7)

**Comment by imobachgs** [comment]
This one is a known issue. There has been some discussion about how `sudo` should be configured for (open)SUSE distributions and we will adapt Agama to work properly rather soon.

**Comment by imobachgs** [comment]
Related to #1418. We should close all these issues once we implement the new behavior.

**Comment by imobachgs** [comment]
WIth the latest changes in the workflow, the user should not end up in that situation. Once the sudo behavior is clarified, we will adjust Agama accordingly.

Thanks!
