### ISSUE TITLE
Network question isn't shown in the UI, blocks install

### ISSUE THREAD

**Issue by vasi** [agama-project/agama#1820]
What I did:
* Started an install of Slowroll from the Nov 29 agama x64 installer, in VMware Workstation.
* At some point during package installation, the network cut out for a second, and the number of packages in the web UI stopped going up.

What I expected:
* The installer asks me in the web UI whether to retry after a network error.
* After retrying, the installer is able to finish successfully.

What happened:
* Nothing interesting was displayed in the web UI: no error message, no dialog. Package installation just appeared stalled.
* Checked the logs with journalctl, and there was a message "waiting for questions to be answered"
* Checked `agama questions list`, and it showed a question about the network error. But there was no indication in the UI.
* It was unclear what I should do at this point, so I aborted the install.

Notes:
* There's probably some way to provide the answer at the CLI, but I don't know what it is.

**Comment by imobachgs** [comment]
Hi! Thanks for reporting this problem. There is a problem with the UI and we are not tracking questions during installation progress. We will fix the issue.

**Comment by vasi** [comment]
Thanks! I'm really excited for the future of Agama, appreciate all your work.
