### ISSUE TITLE
Pressing Select at the very first step stuck in

### ISSUE THREAD

**Issue by vajdao** [agama-project/agama#1853]
When agama launches, it offers the selection of distros.

Yesterday I tried it within VBox so I was like, okay maybe its VBox, but today I tried using agama on an actual hardware and, whenever I select for example Leap and press "Select" button at the bottom right, nothing happens, it just brings me in a white blank background, nothing else. I have to press Cancel, to get back to the first step, then select another distro, for example Tumbleweed, hit Select again, and I'm in Leap's installer (notice that I selected Tumbleweed for the second time) - some sneaky bug slipped in it seems

**Comment by dgdavid** [comment]
Thanks for reporting it @vajdao 

It's really weird, and the first time we get such a report. I'll take a look when time permits, but would be nice to know if you're able to reproduce it and, even better, to download the logs and share them here.

**Comment by vajdao** [comment]
> Thanks for reporting it @vajdao 
> 
> It's really weird, and the first time we get such a report. I'll take a look when time permits, but would be nice to know if you're able to reproduce it and, even better, to download the logs and share them here.

You're welcome. Sure later today I will upload the logs. And yes it's always reproducible

**Comment by dgdavid** [comment]
> I will upload the logs in the upcoming days when I'll have some extra freetime.
> And yes it's always reproducible

Don't worry, I have been able to reproduce it by using the latest ISO. 

I'll ping you back once it is fixed.

Thank you!

**Comment by vajdao** [comment]
> > I will upload the logs in the upcoming days when I'll have some extra freetime.
> > And yes it's always reproducible
> 
> Don't worry, I have been able to reproduce it by using the latest ISO.
> 
> I'll ping you back once it is fixed.
> 
> Thank you!

Sweet thanks for testing it on your end too :)

You're welcome. Glad I could help

**Comment by dgdavid** [comment]
After having a look to the logs, I think it is closely related to the issue fixed by https://github.com/agama-project/agama/pull/1854

> Dec 23 21:10:26 agama agamactl[2966]: [ERROR]: manager: Startup error: #<NoMethodError: undefined method `GetConfig' for DBus interface `' on object `/org/opensuse/Agama/Storage1'>. Backtrace: ["/usr/lib64/ruby/gems/3.3.0/gems/ruby-dbus-0.23.1/lib/dbus/proxy_object.rb:154:in `method_missing'", ...

So, let's wait a bit until next ISO is generated to see if the problem has gone.

**Comment by dgdavid** [comment]
I've tested it today with the latest ISO and it works again as expected :tada:
