### ISSUE TITLE
The localization section in the overview does not load

### ISSUE THREAD

**Issue by imobachgs** [agama-project/agama#706]
It happens sporadically, but the localization section on the overview page does not load sometimes.

![localization](https://github.com/openSUSE/agama/assets/15836/1d5b26a2-847e-424f-9b4f-56f50548dabd)

If you reload (or visit the "localization" section and go back again), everything works. Having the logs from the browser would help. Here is the error from the devtools:

![localization-error](https://github.com/openSUSE/agama/assets/15836/40f8a918-e471-42eb-bdc3-c5834d8046c3)

**Comment by nsundriyal62** [comment]
i can solve this bug
can you assign this to me

**Comment by imobachgs** [comment]
Hi @nsundriyal62,

OK, perfect, I am assigning the issue to you. Please, let me know if you need help.

Regards,
Imo

**Comment by nsundriyal62** [comment]
@imobachgs ok sir

**Comment by imobachgs** [comment]
Hi @nsundriyal62,

While debugging another problem, I found the cause of this bug. There are three D-Bus services ([org.opensuse.Agama.Locale1](https://github.com/openSUSE/agama/blob/e6aff502e112f1c3e0dd78ec83dc6c597b44e4a9/rust/share/org.opensuse.Agama.Locale1.service), [org.opensuse.Agama.Network1](https://github.com/openSUSE/agama/blob/e6aff502e112f1c3e0dd78ec83dc6c597b44e4a9/rust/share/org.opensuse.Agama.Network1.service) and [org.opensuse.Agama.Questions1](https://github.com/openSUSE/agama/blob/e6aff502e112f1c3e0dd78ec83dc6c597b44e4a9/rust/share/org.opensuse.Agama.Questions1.service)) that are implemented in the same binary. The problem is that systemd tries to start all of them almost at the same time, so there are several instances of `agama-dbus-server` fighting for the bus.

We have several options to fix this problem:

1) Use a lockfile (or a pidfile) to avoid conflicts. If the service is started, there is no need to start it again.
2) Extend the `agama-dbus-server` to start just one service at a time (e.g., `agama-dbus-server locale`).
3) Use a single service (`org.opensuse.Agama1`), although that name is already taken).

Unless you have already done some work, I would take this one. Otherwise, please, let me know which is the status.

Thanks!

**Comment by nsundriyal62** [comment]
sorry to say but this is untouched right now. i am stucked in some other issues.

so if its urgent then go for it anotherwise i will solve in next 2 to 3 days

sorry :(

**Comment by mvidner** [comment]
> There are three D-Bus services ([org.opensuse.Agama.Locale1](https://github.com/openSUSE/agama/blob/e6aff502e112f1c3e0dd78ec83dc6c597b44e4a9/rust/share/org.opensuse.Agama.Locale1.service), [org.opensuse.Agama.Network1](https://github.com/openSUSE/agama/blob/e6aff502e112f1c3e0dd78ec83dc6c597b44e4a9/rust/share/org.opensuse.Agama.Network1.service) and [org.opensuse.Agama.Questions1](https://github.com/openSUSE/agama/blob/e6aff502e112f1c3e0dd78ec83dc6c597b44e4a9/rust/share/org.opensuse.Agama.Questions1.service)) that are implemented in the same binary. The problem is that systemd tries to start all of them almost at the same time, so there are several instances of `agama-dbus-server` fighting for the bus.

Yes. Originally we took advantage of the fact that the D-Bus libraries allow us to register multiple D-Bus services (well-known names) in a single program/process, be it on multiple connections (from Rust) or on a single connection (in Ruby). 
(See D-Bus Specification: [Message Bus Names](https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-names) and the spec has a detailed idea about how to handle scenarios more complex than 1:1 process:name, see [RequestName](https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-request-name).)

But **systemd activation** only cares about one [`BusName`](https://www.freedesktop.org/software/systemd/man/systemd.service.html#BusName=) which is a major limiting factor for us.
