### ISSUE TITLE
Switching display language via the URL parameter to `es_AR` does not fallback to `es_ES`, it uses English instead

### ISSUE THREAD

**Issue by lslezak** [agama-project/agama#860]
## Problem

- The UI language can be switched by the URL parameter `?lang=es_ES` to Spanish, that works fine
- But when the requested language is not supported it falls back to English, not to a similar language
- Example: `?lang=es_AR` (Spanish in Argentina) is not directly supported, but it should fallback to `es_ES` as it is probably very close, definitely much closer than English

**Comment by dgdavid** [comment]
@nagu165, 

Just out of curiosity. Did you have a look to this? Your answer at https://github.com/openSUSE/agama/issues/932#issuecomment-1912421668 made me though you will try it.

**Comment by nagu165** [comment]
> @nagu165,
> 
> Just out of curiosity. Did you have a look to this? Your answer at [#932 (comment)](https://github.com/openSUSE/agama/issues/932#issuecomment-1912421668) made me though you will try it.

yes sir, I did.
I also tried to solve the issue but couldn't solve it properly. I had exams going on so kept it on hold. I will try this again.
Thank you.

**Comment by imobachgs** [comment]
> Hello sir, I am really sorry for no response. I have tried to solve the issue but i couldn't. so i think i need to learn a lot. I'll start contributing again once i feel confident. Thank you so much for helping me a lot.

That's no problem. Feel free to try it again in the future. Thanks for your interest in the project. Good luck!

**Comment by imobachgs** [comment]
I will fix this while working on [bsc#1233160](https://bugzilla.suse.com/show_bug.cgi?id=1233160).

**Comment by imobachgs** [comment]
Fixed with #1746.
