### ISSUE TITLE
Deregister shortcut

### ISSUE THREAD

**Issue by joseivanlopez** [agama-project/agama#871]
If a product was already registered and you try to select a new product, then a popup is shown indicating that the product must be deregistered first.

![localhost_8080_ (24)](https://github.com/openSUSE/agama/assets/1112304/30fa6b75-e004-4311-acba-1e798c385987)

This popup could offer a button for deregistering the product and open the registration form.

Note that the deregistration could fail. In that case, the popup has to show the error instead of opening the registration form.

**Comment by ShatilKhan** [comment]
Please assign me this issue @joseivanlopez

**Comment by dgdavid** [comment]
Hi @ShatilKhan,

Thanks a lot for jumping into the project. Appreciated.

Sure, you can go ahead with this issue if you want. Please, ask for help if you get stuck at any time.

Enjoy!

**Comment by ShatilKhan** [comment]
Hey @dgdavid apologies for the delay 
I tried running using these command
```
$ git clone https://github.com/openSUSE/agama
$ cd agama
$ ./setup.sh
```

Doesn't seem to work, I opened my localhost , but there was nothing
It didn't show any error

**Comment by dgdavid** [comment]
Hi @ShatilKhan,

Where are you running the `setup.sh` script? Asking because `setup.sh` is expected to run only in openSUSE Tumbleweed systems, as @imobachgs replied in https://github.com/openSUSE/agama/discussions/876#discussioncomment-7597243

Let me quote a [recent comment](https://github.com/openSUSE/agama/issues/932?notification_referrer_id=NT_kwDOABnQ4LI4Nzc5OTU5MTgxOjE2OTE4NzI&notifications_query=repo%3AopenSUSE%2Fagama#issuecomment-1863007573) from @joseivanlopez that might help you

> For running Agama you need to start both the Agama services (backend) and the web UI. Are you running the Agama services?
> 
> I would suggest to create a virtual machine and use it to run our [live iso image](https://github.com/openSUSE/agama?tab=readme-ov-file#live-iso-image).
> 
> Once the Agama live image is booted in your virtual machine, you can run the web UI from your git clone:
> 
> ```
> $ git clone https://github.com/openSUSE/agama
> $ cd agama/web
> $ npm install
> $ COCKPIT_TARGET=<virtual-machine-ip> npm run server
> ```
> 
> Then point your browser to _https://localhost:8080/_. Probably you will be requested to enter username/password. If so, use root/linux.
> 
> Please, try it and let me know if it works. We can try another approach if it does not work. Thanks!

As he said there, please try it and don't hesitate on asking us whatever you need for getting the _development environment_ ready for start having fun.

**Comment by ShatilKhan** [comment]
Thanks @dgdavid , just found the comment 
I'm running on windows (WSL2) 
So I suppose I'm supposed to actually download the openSUSE Build Service right?
Can you suggest the right version to download?
![image](https://github.com/openSUSE/agama/assets/52494840/11710c62-6683-4544-91d4-dfd6a94245f8)

**Comment by ShatilKhan** [comment]
Thanks @imobachgs! 
I'll follow the instructions & let you know

**Comment by ShatilKhan** [comment]
I've been trying to run agma through VMWare but it keeps getting stuck on the start screen
![image](https://github.com/openSUSE/agama/assets/52494840/eeca4572-3ff8-4afc-bf53-c0f3f7689fd0)

**Comment by dgdavid** [comment]
@ShatilKhan,

Sorry for the late answer. I overlooked your last comment until now.

Do you still having problems for running Agama?

**Comment by ShatilKhan** [comment]
Yes
It would be great to get some help with setting the project up
I am using VM Ware
As you can see from the screenshot, the screen freezes when I try to start agma

**Comment by joseivanlopez** [comment]
> Yes It would be great to get some help with setting the project up I am using VM Ware As you can see from the screenshot, the screen freezes when I try to start agma

It seems you are using VirtualBox, right? Anyway, could you please paste the link of the image you are trying to boot? Are you running VirtualBox from WSL or from Windows?

**Comment by ShatilKhan** [comment]
Image : https://download.opensuse.org/repositories/systemsmanagement:/Agama:/Devel/images/iso/agama-live.x86_64-7.0.0-ALP-Build1.28.iso

I'm running from Windows 10 (64 bit)

**Comment by imobachgs** [comment]
Given that the image matches your architecture, I expect it to boot correctly on VirtualBox. Do you know if a regular openSUSE Tumbleweed image works? Could you try with a newer image?

**Comment by imobachgs** [comment]
The original issue, the shortcut to deregister the system, is not relevant anymore. We plan to bring back the registration support soon.
